{
 "title": "Reversy Klin - Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT name\nFROM config.endpoints\nORDER BY id ASC;"
   },
   {
    "name": "endpoint_id",
    "query": "SELECT id\nFROM config.endpoints\nWHERE name = '${endpoint}';"
   },
   {
    "name": "tag_table",
    "label": "Tag Table",
    "query": "SELECT name\nFROM config.tag_tables\nWHERE name IN (\n    SELECT unnest(\n            string_to_array(\n                replace(replace(replace(tag_tables, '[', ''), ']', ''), '\"', ''), ','\n            )\n        )\n    FROM config.endpoints\n    WHERE name = '${endpoint}'\n);"
   },
   {
    "name": "data_table",
    "label": "Table",
    "query": "SELECT data_table\nFROM config.tag_tables\nWHERE name = '${tag_table}'"
   },
   {
    "name": "lables",
    "label": "Lables",
    "query": "SELECT DISTINCT label\nFROM tags.${tag_table}\nORDER BY label ASC;"
   },
   { "name": "time_range", "label": "Time Range", "query": "SELECT (${__to} - ${__from})" },
   { "name": "aggregation", "label": "Aggregation", "query": "None, Interval" },
   {
    "name": "interval_text",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,2h,3h,6h,12h,1d,7d,14d,30d,60d,90d,120d,180d,240d,360d"
   },
   {
    "name": "interval_ms",
    "query": "SELECT \n    CASE \n        WHEN '${aggregation}' = 'None' THEN 0\n        ELSE EXTRACT(EPOCH FROM '${interval_text}'::INTERVAL) * 1000\n    END AS interval_ms;\n"
   },
   {
    "name": "title",
    "query": "SELECT machine\nFROM config.endpoints\nWHERE id = ${endpoint_id} "
   },
   {
    "name": "from_text",
    "query": "SELECT TO_CHAR(TO_TIMESTAMP($__from / 1000), 'YYYY-MM-DD HH24:MI:SS')"
   },
   {
    "name": "to_text",
    "query": "SELECT TO_CHAR(TO_TIMESTAMP($__to / 1000), 'YYYY-MM-DD HH24:MI:SS')"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"text-align: left; font-weight: 500; margin-top: 50px; margin-bottom: 50px;\">\n    \n</h1>\n"
   }
  },
  {
   "title": "Endpoint Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Address\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Machine Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT machine\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id} "
    }
   ]
  },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__from}/1000) AS \"From\"\r\n"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "First ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Endpoint ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Endpoint Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT protocol\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__to}/1000) AS \"To\"\r\n"
    }
   ]
  },
  {
   "title": "Last ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cycle Disabled Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TStop\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TCY\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Time Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (${__to} - ${__from})/1000\r\n"
    }
   ]
  },
  {
   "title": "Waiting Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TWait\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Unavailability Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TOff\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TCY AS \"Cycle Time\", \r\n  TStop AS \"Cycle Disabled Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TCO AS \"Combustion Time\", \r\n  TI AS \"Inversion Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TWait1 AS \"Drawer Sampling\",\r\n  TWait2 AS \"Valves Maintenance\",\r\n  TWait3 AS \"Hydraulic Oil Unit Maintenance\",\r\n  TWait4 AS \"Hydraulic Oil Plant Maintenance\",\r\n  TWait5 AS \"Blower Maintenance\",\r\n  TWait6 AS \"Skip Maintenance\",\r\n  TWait7 AS \"Weighed Hopper Calibration\",\r\n  TWait8 AS \"Coal Weighed Tank Calibration\",\r\n  TWait9 AS \"Other Maintenance\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TOff1 AS \"Mechanical Issue Time\",\r\n  TOff2 AS \"Electrical Issue Time\",\r\n  TOff3 AS \"Process Issue Time\",\r\n  TOff4 AS \"Other Issue Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Combustion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TCO\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Fuel Supply Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TFS\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Inversion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TI\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  { "title": "Times Heatmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    TStop\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TStop) AS \"Cycle Disabled\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    TWait1,\r\n    TWait2,\r\n    TWait3,\r\n    TWait4,\r\n    TWait5,\r\n    TWait6,\r\n    TWait7,  \r\n    TWait8,\r\n    TWait9 \r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time AS \"To Time\",\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TWait1) AS \"Drawer Sampling\",\r\n  SUM(TWait2) AS \"Valves Maintenance\",\r\n  SUM(TWait3) AS \"Hydraulic Oil Unit Maintenance\",\r\n  SUM(TWait4) AS \"Hydraulic Oil Plant Maintenance\",\r\n  SUM(TWait5) AS \"Blower Maintenance\",\r\n  SUM(TWait6) AS \"Skip Maintenance\",\r\n  SUM(TWait7) AS \"Weighed Hopper Calibration\",\r\n  SUM(TWait8) AS \"Coal Weighed Tank Calibration\",\r\n  SUM(TWait9) AS \"Other Maintenance\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    TOff1, \r\n    TOff2,\r\n    TOff3,\r\n    TOff4\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TOff1) AS \"Mechanical Issue Time\",\r\n  SUM(TOff2) AS \"Electrical Issue Time\",\r\n  SUM(TOff3) AS \"Process Issue Time\",\r\n  SUM(TOff4) AS \"Other Issue Time\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Limestone / Lime",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LCY, LSCYsp, LSCYpv\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  SUM(LSCYsp) AS \"Limestone Setpoint\",\r\n  SUM(LSCYpv) AS \"Limestone\",\r\n  SUM(LCY) AS \"Lime\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total - Limestone",
   "type": "stat",
   "description": "The value is compared to the value from the preceding period of the same duration",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(LSCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(LSCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Mean Rate - Limestone",
   "type": "stat",
   "description": "Rate calculated over the entire selected period",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at AS time_start,\r\n    created_at + ((TCY + TStop) * INTERVAL '1 second') AS time_end,\r\n    LSCYpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at) \r\n)\r\nSELECT\r\n  SUM(value) / extract(epoch from (max(time_end) - min(time_start))) * 3.6 AS \"Limestone Rate\"\r\nFROM temp\r\n  "
    }
   ]
  },
  {
   "title": "Mean Rate - Lime",
   "type": "stat",
   "description": "Rate calculated over the entire selected period",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at AS time_start,\r\n    created_at + ((TCY + TStop) * INTERVAL '1 second') AS time_end,\r\n    LCY AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at) \r\n)\r\nSELECT\r\n  SUM(value) / extract(epoch from (max(time_end) - min(time_start))) * 3.6 AS \"Lime Rate\"\r\nFROM temp\r\n  "
    }
   ]
  },
  {
   "title": "Total - Lime",
   "type": "stat",
   "description": "The value is compared to the value from the preceding period of the same duration",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous' AS period,\r\n    SUM(LCY) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'current' AS period,\r\n    SUM(LCY) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Nominal Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "tpd" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    NP\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time AS time_start,\r\n  time + (${interval_ms} * INTERVAL '1 millisecond') AS time_end,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(NP) AS \"Nominal Production\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Nominal Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "tpd" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(NP) AS average\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(NP) AS average\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Nominal Production",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    NP AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  { "title": "Fuel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Heat Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kcal/kg" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    HCpv, HCsp\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(HCsp) AS \"Heat Consumption Setpoint\",\r\n  AVG(HCpv) AS \"Heat Consumption\"\r\n  \r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Heat Consumtion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kcal/kg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(HCpv) AS mean\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(HCpv) AS mean\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Heat Consumption",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    HCpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Nm3" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    FCYpv, FCYsp\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  SUM(FCYsp) AS \"Fuel for Cycle Setpoint\",\r\n  SUM(FCYpv) AS \"Fuel for Cycle\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Total - Fuel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Nm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(FCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(FCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Fuel",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    FCYpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    FFpv, FFsp\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(FFsp) AS \"Fuel Flow Setpoint\",\r\n  AVG(FFpv) AS \"Fuel Flow\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(FFpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(FFpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Fuel Flow",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    FFpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  { "title": "Combustion Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Combustion Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    CAF\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(CAF) AS \"Combustion Air Flow\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Combustion Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(CAF) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(CAF) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Fuel Flow",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    CAF AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Combustion Air Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    EANpv, EANsp\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(EANsp) AS \"Combustion Air Index Setpoint\",\r\n  AVG(EANpv) AS \"Combustion Air Index\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Combustion Air Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(EANpv) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(EANpv) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Combustion Air Index",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 116 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    EANpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Combustion Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    CMB1pv, CMB2pv, CMB3pv\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(CMB1pv) AS \"Combustion Air Blower 1 - Speed\",\r\n  AVG(CMB2pv) AS \"Combustion Air Blower 2 - Speed\",\r\n  AVG(CMB3pv) AS \"Combustion Air Blower 3 - Speed\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Combustion Air Blower Speed",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 121 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    CMB1pv AS value1,\r\n    CMB2pv AS value2,\r\n    CMB3pv AS value3\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Blower 1 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 1 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 2 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 2 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 3 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value3 AS \"Value\", created_at FROM data\r\nWHERE value3 = (SELECT MIN(value3) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 3 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value3 AS \"Value\", created_at FROM data\r\nWHERE value3 = (SELECT MAX(value3) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Combustion Air Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    CBAP\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(CBAP) AS \"Combustion Air Pressure\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Combustion Air Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(CBAP) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(CBAP) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Combustion Air Pressure",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 133 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    CBAP AS value1\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  { "title": "Cool Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Lime Cooling Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LCAF\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LCAF) AS \"Lime Cooling Air Flow\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Lime Cooling Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "Nm³/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(LCAF) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(LCAF) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Cooling Air Flow",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 142 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LCAF AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Cooling Air Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    ALCsp, ALCpv\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(ALCsp) AS \"Lime Cooling Air Ratio Setpoint\",\r\n  AVG(ALCpv) AS \"Lime Cooling Air Ratio\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Lime Cooling Air Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(ALCpv) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(ALCpv) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Cooling Air Ratio",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 150 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    ALCpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MIN(value) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value AS \"Value\", created_at FROM data\r\nWHERE value = (SELECT MAX(value) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Cooling Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LCB1pv, LCB2pv\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LCB1pv) AS \"Lime Cooling Air Blower 1 - Speed\",\r\n  AVG(LCB2pv) AS \"Lime Cooling Air Blower 2 - Speed\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Cooling Air Blower Speed",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LCB1pv AS value1,\r\n    LCB2pv AS value2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Blower 1 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 1 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 2 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Blower 2 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Cooling Air Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    CLAP, LCAPS1, LCAPS2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LCAPS1) AS \"Shaft 1 - Lances cooling / Final injection air pressure\",\r\n  AVG(LCAPS2) AS \"Shaft 2 - Lances cooling / Final injection air pressure\",\r\n  AVG(CLAP) AS \"Lime Cooling Air Pressure\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Mean - Lime Cooling Air Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(CLAP) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(CLAP) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Cooling Air Pressure",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 166 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    CLAP AS value1,\r\n    LCAPS1 AS value2,\r\n    LCAPS2 AS value3\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'Global - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Global - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Shaft 1 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Shaft 1 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Shaft 2 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value3 AS \"Value\", created_at FROM data\r\nWHERE value3 = (SELECT MIN(value3) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'Shaft 2 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value3 AS \"Value\", created_at FROM data\r\nWHERE value3 = (SELECT MAX(value3) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "title": "Lime Temperature - Skip Side - Shaft 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LT1, LT8\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LT1) AS \"Skip side Shaft 1 - LT1 (Inspection door ZS204101)\",\r\n  AVG(LT8) AS \"Skip side Shaft 1 - LT8 (Inspection door ZS204108)\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Skip Side Shaft 1 - LT1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT1) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Skip Side Shaft 1 - LT8",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT8) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Temperature - Skip Side Shaft 1",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 178 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LT1 AS value1,\r\n    LT2 AS value2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'LT1 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT1 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT8 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT8 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Temperature - Skip Side - Shaft 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LT9, LT16\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LT9) AS \"Skip side Shaft 2 - LT9 (Inspection door ZS204101)\",\r\n  AVG(LT16) AS \"Skip side Shaft 2 - LT16 (Inspection door ZS204108)\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Skip Side Shaft 2 - LT9",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT9) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Skip Side Shaft 2  - LT16",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT16) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Temperature - Skip Side Shaft 2",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 187 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LT9 AS value1,\r\n    LT16 AS value2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'LT9 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT9 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Temperature - Pipe Side - Shaft 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LT4, LT5\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LT4) AS \"Pipe side Shaft 1 - LT4 (Inspection door ZS204104)\",\r\n  AVG(LT5) AS \"Pipe side Shaft 1 - LT5 (Inspection door ZS204105)\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Pipe Side Shaft 1 - LT4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT4) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Pipe Side Shaft  1  - LT5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT5) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Temperature - Pipe Side Shaft 1",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 196 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LT9 AS value1,\r\n    LT16 AS value2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'LT9 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT9 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Lime Temperature - Pipe Side - Shaft 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 minute' \r\n        THEN created_at\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LT12, LT13\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(LT12) AS \"Pipe side Shaft 2 - LT12 (Inspection door ZS204104)\",\r\n  AVG(LT13) AS \"Pipe side Shaft 2 - LT13 (Inspection door ZS204105)\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Pipe Side Shaft 2 - LT12",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT12) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Pipe Side Shaft 2 - LT13",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'selected_interval' AS period,\r\n    AVG(LT13) AS value\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Boundary Cycles - Lime Temperature - Pipe Side Shaft 2",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 205 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    created_at,\r\n    CY, \r\n    LT9 AS value1,\r\n    LT16 AS value2\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at)\r\n)\r\n(SELECT 'LT9 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MIN(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT9 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value1 AS \"Value\", created_at FROM data\r\nWHERE value1 = (SELECT MAX(value1) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Min' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MIN(value2) FROM data) ORDER BY created_at DESC LIMIT 1)\r\nUNION ALL\r\n(SELECT 'LT16 - Max' AS \"Type\", TO_CHAR(created_at, 'YYYY-MM-DD') AS \"Date\", TO_CHAR(created_at, 'HH24:MI:SS') AS \"Time\", CY AS \"Cycle\", value2 AS \"Value\", created_at FROM data\r\nWHERE value2 = (SELECT MAX(value2) FROM data) ORDER BY created_at DESC LIMIT 1)"
    }
   ]
  },
  {
   "title": "Pressures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 },
   "collapsed": true
  },
  {
   "title": "Other Mesurements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 212 },
   "collapsed": true
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 214 },
   "targets": [
    {
     "rawSql": "SELECT * \r\nFROM ${data_table}\r\nWHERE endpoint = $endpoint_id \r\n  AND $__timeFilter(created_at) \r\nORDER BY created_at DESC"
    }
   ]
  }
 ]
}