{
 "title": "Brasiera 1",
 "time": { "from": "2024-11-29T15:27:24.062Z", "to": "2024-11-29T15:37:24.062Z" },
 "refresh": "5s",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT temperature, ora FROM brasiera_con_mixer_vapore where id = 1 ORDER BY ora DESC"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature, pressure FROM brasiera_con_mixer_vapore Where ID = 1 ORDER BY ora desc limit 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT pressure, ora FROM brasiera_con_mixer_vapore where id = 1 ORDER BY ora DESC"
    }
   ]
  },
  {
   "title": "Consumi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT ora, SUM(consumi) FROM brasiera_con_mixer_vapore GROUP BY ora LIMIT 50 "
    }
   ]
  },
  {
   "title": "Consumi globali macchina",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(consumi) FROM brasiera_con_mixer_vapore where id=1"
    }
   ]
  },
  {
   "title": "ON / OFF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT ora, on_off FROM brasiera_con_mixer_vapore where id=1 order by ora desc"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 6, "w": 20, "x": 0, "y": 37 } }
 ]
}