{
 "title": "Reversy Klin - Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT name\nFROM config.endpoints\nORDER BY id ASC;"
   },
   {
    "name": "endpoint_id",
    "query": "SELECT id\nFROM config.endpoints\nWHERE name = '${endpoint}';"
   },
   {
    "name": "tag_table",
    "label": "Tag Table",
    "query": "SELECT name\nFROM config.tag_tables\nWHERE name IN (\n    SELECT unnest(\n            string_to_array(\n                replace(replace(replace(tag_tables, '[', ''), ']', ''), '\"', ''), ','\n            )\n        )\n    FROM config.endpoints\n    WHERE name = '${endpoint}'\n);"
   },
   {
    "name": "data_table",
    "label": "Table",
    "query": "SELECT process_table\nFROM config.tag_tables\nWHERE name = '${tag_table}'"
   },
   {
    "name": "lables",
    "label": "Lables",
    "query": "SELECT DISTINCT label\nFROM tags.${tag_table}\nORDER BY label ASC;"
   },
   {
    "name": "time_range",
    "label": "Time Range",
    "query": "SELECT (${__to} - ${__from})/1000"
   },
   {
    "name": "interval_text",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d,60d,90d,120d,180d,240d,360d"
   },
   {
    "name": "interval_ms",
    "query": "SELECT EXTRACT(EPOCH FROM '${interval_text}'::INTERVAL)*1000"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"text-align: left; font-weight: 500; margin-top: 50px; margin-bottom: 50px;\">\n    \n</h1>\n"
   }
  },
  {
   "title": "Endpoint Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Address\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Machine Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT machine\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id} "
    }
   ]
  },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__from}/1000) AS \"From\"\r\n"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "First ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Endpoint ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Endpoint Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT protocol\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__to}/1000) AS \"To\"\r\n"
    }
   ]
  },
  {
   "title": "Last ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CY \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * \r\nFROM ${data_table}\r\nWHERE endpoint = $endpoint_id \r\n  AND $__timeFilter(created_at) \r\nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Cycle Disabled Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TStop\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TCY\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Time Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (${__to} - ${__from})/1000\r\n"
    }
   ]
  },
  {
   "title": "Waiting Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TWait\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Unavailability Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TOff\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TCY AS \"Cycle Time\", \r\n  TStop AS \"Cycle Disabled Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TCO AS \"Combustion Time\", \r\n  TI AS \"Inversion Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TWait1 AS \"Drawer Sampling\",\r\n  TWait2 AS \"Valves Maintenance\",\r\n  TWait3 AS \"Hydraulic Oil Unit Maintenance\",\r\n  TWait4 AS \"Hydraulic Oil Plant Maintenance\",\r\n  TWait5 AS \"Blower Maintenance\",\r\n  TWait6 AS \"Skip Maintenance\",\r\n  TWait7 AS \"Weighed Hopper Calibration\",\r\n  TWait8 AS \"Coal Weighed Tank Calibration\",\r\n  TWait9 AS \"Other Maintenance\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TOff1 AS \"Mechanical Issue Time\",\r\n  TOff2 AS \"Electrical Issue Time\",\r\n  TOff3 AS \"Process Issue Time\",\r\n  TOff4 AS \"Other Issue Time\"\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Combustion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TCO\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Fuel Supply Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TFS\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Inversion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT TI\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${__interval_ms} * INTERVAL '1 millisecond', created_at + ((TCY + TStop) * INTERVAL '1 second'), TIMESTAMP 'epoch')\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n    END AS time,\r\n    TStop\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TStop) AS \"Cycle Disabled\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${__interval_ms} * INTERVAL '1 millisecond', created_at + ((TCY + TStop) * INTERVAL '1 second'), TIMESTAMP 'epoch')\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n    END AS time,\r\n    TWait1,\r\n    TWait2,\r\n    TWait3,\r\n    TWait4,\r\n    TWait5,\r\n    TWait6,\r\n    TWait7,  \r\n    TWait8,\r\n    TWait9 \r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time AS \"To Time\",\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TWait1) AS \"Drawer Sampling\",\r\n  SUM(TWait2) AS \"Valves Maintenance\",\r\n  SUM(TWait3) AS \"Hydraulic Oil Unit Maintenance\",\r\n  SUM(TWait4) AS \"Hydraulic Oil Plant Maintenance\",\r\n  SUM(TWait5) AS \"Blower Maintenance\",\r\n  SUM(TWait6) AS \"Skip Maintenance\",\r\n  SUM(TWait7) AS \"Weighed Hopper Calibration\",\r\n  SUM(TWait8) AS \"Coal Weighed Tank Calibration\",\r\n  SUM(TWait9) AS \"Other Maintenance\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${__interval_ms} * INTERVAL '1 millisecond', created_at + ((TCY + TStop) * INTERVAL '1 second'), TIMESTAMP 'epoch')\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n      WHEN ${__interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at + ((TCY + TStop) * INTERVAL '1 second'))\r\n    END AS time,\r\n    TOff1, \r\n    TOff2,\r\n    TOff3,\r\n    TOff4\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from MIN(created_at))*1000)::TEXT AS from_time,\r\n  (extract(epoch from MAX(created_at))*1000)::TEXT AS to_time,\r\n  SUM(TOff1) AS \"Mechanical Issue Time\",\r\n  SUM(TOff2) AS \"Electrical Issue Time\",\r\n  SUM(TOff3) AS \"Process Issue Time\",\r\n  SUM(TOff4) AS \"Other Issue Time\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Limestone / Lime",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${__interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LSCYpv,\r\n    LCY\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${__interval_ms})::TEXT AS to_time,\r\n  SUM(LSCYpv) AS \"Total Limestone\",\r\n  SUM(LCY) AS \"Total Lime\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Nominal Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "tpd" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    NP\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time AS time_start,\r\n  time + (${interval_ms} * INTERVAL '1 millisecond') AS time_end,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  AVG(NP) AS \"Nominal Production\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Nominal Production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "tpd" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    AVG(NP) AS average\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    AVG(NP) AS average\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Lime Produced",
   "type": "stat",
   "description": "The value is compared to the value from the preceding period of the same duration",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous' AS period,\r\n    SUM(LCY) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'current' AS period,\r\n    SUM(LCY) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Lime Rate",
   "type": "stat",
   "description": "Rate calculated over the entire selected period",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at AS time_start,\r\n    created_at + ((TCY + TStop) * INTERVAL '1 second') AS time_end,\r\n    LCY AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at) \r\n)\r\nSELECT\r\n  SUM(value) / extract(epoch from (max(time_end) - min(time_start))) * 3.6 AS \"Lime Rate\"\r\nFROM temp\r\n  "
    }
   ]
  },
  {
   "title": "Limestone / Lime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '1 day' \r\n        THEN date_bin(${interval_ms} * INTERVAL '1 millisecond', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval_ms} * INTERVAL '1 millisecond' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n    END AS time,\r\n    LCY, LSCYsp, LSCYpv\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  (extract(epoch from time) * 1000)::TEXT  AS from_time,\r\n  ((extract(epoch from time) * 1000) + ${interval_ms})::TEXT AS to_time,\r\n  SUM(LCY) AS \"Lime x Cycle\",\r\n  SUM(LSCYsp) AS \"Limestone x Cycle Setpoint\",\r\n  SUM(LSCYpv) AS \"Limestone x Cycle\"\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Limestone SP",
   "type": "stat",
   "description": "The value is compared to the value from the preceding period of the same duration",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(LSCYsp) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(LSCYsp) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Limestone",
   "type": "stat",
   "description": "The value is compared to the value from the preceding period of the same duration",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(LSCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(LSCYpv) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "  Limestone Rate SP",
   "type": "stat",
   "description": "Rate calculated over the entire selected period",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at AS time_start,\r\n    created_at + ((TCY + TStop) * INTERVAL '1 second') AS time_end,\r\n    LSCYsp AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at) \r\n)\r\nSELECT\r\n  SUM(value) / extract(epoch from (max(time_end) - min(time_start))) * 3.6 AS \"Limestone Rate Setpoint\"\r\nFROM temp\r\n  "
    }
   ]
  },
  {
   "title": "Limestone Rate",
   "type": "stat",
   "description": "Rate calculated over the entire selected period",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at AS time_start,\r\n    created_at + ((TCY + TStop) * INTERVAL '1 second') AS time_end,\r\n    LSCYpv AS value\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n    AND $__timeFilter(created_at) \r\n)\r\nSELECT\r\n  SUM(value) / extract(epoch from (max(time_end) - min(time_start))) * 3.6 AS \"Limestone Rate\"\r\nFROM temp\r\n  "
    }
   ]
  },
  { "title": "Fuel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, heat_consumption_setpoint, heat_consumption\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n"
    }
   ]
  },
  {
   "title": "Heat Setpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(heat_consumption_setpoint) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(nominal_prod) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Natural Gas Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Heat Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Heat Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 103 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cycle_id, heat_consumption_setpoint, heat_consumption\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Natural Gas Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption\r\nFROM (\r\n    SELECT created_at, heat_consumption\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Fuel Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 108 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_cycle_setpoint, fuel_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle\r\nFROM (\r\n    SELECT created_at, fuel_cycle\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Natural Gas Regulator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT natural_gas_output_regulator\r\nFROM (\r\n    SELECT created_at, natural_gas_output_regulator\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Fuel Flow Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 117 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_flow_setpoint, fuel_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow\r\nFROM (\r\n    SELECT created_at, fuel_flow\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  { "title": "Combustion Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Combustion Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 125 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_flow_theo, combustion_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Flow Theo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Waste Gasses Outlet Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_outlet_kiln\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combution Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption\r\nFROM (\r\n    SELECT created_at, heat_consumption\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 130 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 132 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_blower_speed_setpoint, combustion_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Index Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 132 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_index_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 133 },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter, waste_gases_temp_outlet_kiln\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combution Air Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_index\r\nFROM (\r\n    SELECT created_at, combustion_air_index\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Waste Gasses Filter Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combustion Air Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 139 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_index_setpoint, combustion_air_index\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Blower Speed Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Combustion Air Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combution Air Blower Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 143 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_blower_speed\r\nFROM (\r\n    SELECT created_at, combustion_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  { "title": "Cool Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Cool Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 147 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_flow_theo, cool_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 147 },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure, shaft2_lances_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 1 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 150 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM (\r\n    SELECT created_at, cool_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 154 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_blower_speed_setpoint, cool_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 154 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM (\r\n    SELECT created_at, cool_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 155 },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 157 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio\r\nFROM (\r\n    SELECT created_at, cool_air_ratio\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 2 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 158 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft2_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Flow Theoretical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 160 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 161 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_ratio_setpoint, cool_air_ratio\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Lime Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 163 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 164 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  { "title": "Other Mesurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "Strokes Shaft 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 169 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT shaft1_strokes\r\nFROM (\r\n    SELECT created_at, shaft1_strokes\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Strokes Shaft 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 169 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT shaft2_strokes\r\nFROM (\r\n    SELECT created_at, shaft2_strokes\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  }
 ]
}