version: '2.4'

services:
  # Node-RED service for creating and managing automation flows
  nodered:
    image: edge-nodered:0.0.7
    container_name: flow-creator
    restart: unless-stopped  
    ports:
      - "1880:1880"  # Exposes Node-RED web interface
      - "502:502"    # Additional port for external services
    volumes:
      - ./nodered_data:/data  # Persist Node-RED data
      - ./share_files:/home/nodered/node-red-home/node-red-files  # Shared files
    environment:
      - TZ=Europe/Rome  
    networks:
      - proxy-redirect  # Connect to external network

# Persistent volume for storing Node-RED data
volumes:
  nodered_data:
    name: nodered_data

# External network for inter-container communication
networks:
  proxy-redirect:
    external: true
