{
 "title": "Lime Klin - Cycle Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT name\nFROM config.endpoints\nORDER BY id ASC;"
   },
   {
    "name": "endpoint_id",
    "query": "SELECT id\nFROM config.endpoints\nWHERE name = '${endpoint}';"
   },
   {
    "name": "tag_table",
    "label": "Tag Table",
    "query": "SELECT name\nFROM config.tag_tables\nWHERE name IN (\n    SELECT unnest(\n            string_to_array(\n                replace(replace(replace(tag_tables, '[', ''), ']', ''), '\"', ''), ','\n            )\n        )\n    FROM config.endpoints\n    WHERE name = '${endpoint}'\n);"
   },
   {
    "name": "data_table",
    "label": "Table",
    "query": "SELECT process_table\nFROM config.tag_tables\nWHERE name = '${tag_table}'"
   },
   {
    "name": "cycle_select",
    "label": "Cycle ID",
    "query": "SELECT 'Last' AS id\n\nUNION ALL\n\nSELECT cycle_id::text AS id\nFROM ${data_table} \nWHERE endpoint = ${endpoint_id} \n  AND $__timeFilter(created_at) \nORDER BY id DESC"
   },
   {
    "name": "cycle",
    "label": "Cycle ID",
    "query": "WITH cycle_text AS (\n    SELECT\n        CASE\n            WHEN lower('${cycle_select}') = 'last'\n            THEN (\n                SELECT cycle_id::text\n                FROM ${data_table}\n                WHERE endpoint = ${endpoint_id}\n                  AND $__timeFilter(created_at)\n                ORDER BY created_at DESC\n                LIMIT 1\n            )\n            ELSE '${cycle_select}'\n        END AS cycle_id_text\n)\nSELECT cycle_id_text::integer AS selected_cycle_id\nFROM cycle_text;\n"
   },
   {
    "name": "label",
    "label": "Lables",
    "query": "SELECT DISTINCT label\nFROM tags.${tag_table}\nORDER BY label ASC;"
   },
   {
    "name": "tag_name",
    "query": "SELECT DISTINCT name \nFROM tags.${tag_table}\nWHERE label = '${label}'\n"
   },
   {
    "name": "tag_other_name",
    "query": "SELECT DISTINCT name \nFROM tags.${tag_table}\nWHERE label = 'other'\n"
   },
   {
    "name": "tag_other_comment",
    "query": "SELECT DISTINCT comment \nFROM tags.${tag_table}\nWHERE label = 'other'\n"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"text-align: left; font-weight: 500; margin-top: 50px; margin-bottom: 50px;\">\n    \n</h1>\n"
   }
  },
  {
   "title": "Endpoint Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Address\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Machine Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT machine\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id} "
    }
   ]
  },
  {
   "title": "Cycle ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_id \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Shaft",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT shaft_combustion " }
   ]
  },
  {
   "title": "Endpoint ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Endpoint Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT protocol\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Up Time",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_time, cycle_disabled_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  combustion_time, \r\n  inversion_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}\r\n"
    }
   ]
  },
  {
   "title": "Unavailability Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT unavailability_time \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}\r\n"
    }
   ]
  },
  {
   "title": "Waiting Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT waiting_time \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  mechanical_issue_time,\r\n  electrical_issue_time, \r\n  process_issue_time,\r\n  other_issue_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  valves_maint_time,\r\n  hyd_oil_unit_maint_time, \r\n  hyd_oil_plant_maint_time,\r\n  blower_maint_time,\r\n  skip_maint_time,\r\n  limestone_hopper_time,\r\n  other_maint_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Combustion Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Fuel Supply Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_supply_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Inversion Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT inversion_time\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Lime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT created_at, nominal_prod, lime_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Nominal Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT nominal_prod\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
    }
   ]
  },
  {
   "title": "Lime Produced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT lime_cycle\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC\r\n"
    }
   ]
  },
  {
   "title": "Limestone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT created_at, limestone_cycle_setpoint, limestone_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Limestone Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT limestone_cycle_setpoint\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at) \r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Limestone",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT limestone_cycle\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "Combustion Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Combustion Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_flow_theo, combustion_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Flow Theo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Combustion Air Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combution Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_blower_speed_setpoint, combustion_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Index Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_index_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Waste Gasses Outlet Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_outlet_kiln\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combution Air Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_index\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Waste Gasses Filter Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Combustion Air Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT created_at, combustion_air_index_setpoint, combustion_air_index\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Combustion Air Blower Speed Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Combution Air Blower Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_air_blower_speed\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter, waste_gases_temp_outlet_kiln\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  { "title": "Fuel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Fuel Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_cycle_setpoint, fuel_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Natural Gas Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_flow_setpoint, fuel_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Flow Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Natural Gas Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Heat Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT created_at, heat_consumption_setpoint, heat_consumption\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Heat Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Natural Gas Regulator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT natural_gas_output_regulator\r\nFROM (\r\n    SELECT created_at, natural_gas_output_regulator\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "Cool Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Cool Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_flow_theo, cool_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Flow Theoretical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Lime Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 94 },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_blower_speed_setpoint, cool_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 1 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 2 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft2_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 103 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_ratio_setpoint, cool_air_ratio\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Ratio Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 107 },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure, shaft2_lances_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  { "title": "Other Mesurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "${tag_other_name}",
   "type": "stat",
   "description": "${tag_other_comment}",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 111 },
   "repeat": "tag_other_name",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${tag_other_name}\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC "
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}