CREATE OR REPLACE PROCEDURE create_process_values_table()
LANGUAGE plpgsql
AS $$
BEGIN
    -- Check if the table already exists
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
          AND table_name = 'process_values'
    ) THEN
        EXECUTE '
            CREATE TABLE public.process_values (
                id SERIAL PRIMARY KEY,
                progressive_cycle_number INTEGER CHECK (progressive_cycle_number BETWEEN 1 AND 9999),
                shaft_in_combustion INTEGER,
                cycle_time NUMERIC,
                combustion_time NUMERIC,
                inversion_time NUMERIC,
                time_fuel_supply NUMERIC,
                limestone_for_cycle NUMERIC,
                lime_for_cycle NUMERIC,
                nominal_production NUMERIC,
                heat_consumption NUMERIC,
                fuel_for_cycle NUMERIC,
                fuel_flow NUMERIC,
                low_heat_value_air NUMERIC,
                stoichiometric_air NUMERIC,
                combustion_air_flow_theoretical NUMERIC,
                combustion_air_flow NUMERIC,
                combustion_air_index_excess_air NUMERIC,
                combustion_air_blower_speed NUMERIC,
                lime_cooling_air_flow_theoretical NUMERIC,
                lime_cooling_air_flow NUMERIC,
                lime_cooling_air_ratio NUMERIC,
                lime_cooling_air_blower_speed NUMERIC,
                channel_temperature_1 NUMERIC,
                channel_temperature_2 NUMERIC,
                waste_gases_temp_outlet_kiln NUMERIC,
                waste_gases_temp_inlet_kiln_filter NUMERIC,
                shaft1_drawer_pipe_side_lime_temp NUMERIC,
                shaft1_drawer_skip_side_lime_temp NUMERIC,
                shaft2_drawer_pipe_side_lime_temp NUMERIC,
                shaft2_drawer_skip_side_lime_temp NUMERIC,
                combustion_air_pressure NUMERIC,
                lime_cooling_air_pressure NUMERIC,
                channel_air_pressure NUMERIC,
                shaft1_lances_cooling_air_pressure NUMERIC,
                shaft2_lances_cooling_air_pressure NUMERIC,
                shaft1_total_strokes INTEGER,
                shaft2_total_strokes INTEGER,
                natural_gas_temperature NUMERIC,
                natural_gas_pressure NUMERIC,
                natural_gas_output_regulator NUMERIC,
                hydraulic_oil_temperature NUMERIC,
                hydraulic_oil_pressure NUMERIC,
                waiting_time NUMERIC,
                unavailability_time NUMERIC,
                drawer_sampling NUMERIC,
                valves_time_maintenance NUMERIC,
                hydraulic_oil_unit_time_maintenance NUMERIC,
                hydraulic_oil_plant_time_maintenance NUMERIC,
                blower_time_maintenance NUMERIC,
                skip_time_maintenance NUMERIC,
                limestone_weighed_hopper_calibration NUMERIC,
                other_maintenance NUMERIC,
                mechanical_issue NUMERIC,
                electrical_issue NUMERIC,
                process_issue NUMERIC,
                other_issue NUMERIC,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        ';
        RAISE NOTICE 'Table process_values created successfully.';
    ELSE
        RAISE NOTICE 'Table process_values already exists.';
    END IF;
END;
$$;

-- 2. Create the stored procedure to insert data into process_values table
CREATE OR REPLACE PROCEDURE insert_process_value(
    progressive_cycle_number INTEGER,
    shaft_in_combustion INTEGER,
    cycle_time NUMERIC,
    combustion_time NUMERIC,
    inversion_time NUMERIC,
    time_fuel_supply NUMERIC,
    limestone_for_cycle NUMERIC,
    lime_for_cycle NUMERIC,
    nominal_production NUMERIC,
    heat_consumption NUMERIC,
    fuel_for_cycle NUMERIC,
    fuel_flow NUMERIC,
    low_heat_value_air NUMERIC,
    stoichiometric_air NUMERIC,
    combustion_air_flow_theoretical NUMERIC,
    combustion_air_flow NUMERIC,
    combustion_air_index_excess_air NUMERIC,
    combustion_air_blower_speed NUMERIC,
    lime_cooling_air_flow_theoretical NUMERIC,
    lime_cooling_air_flow NUMERIC,
    lime_cooling_air_ratio NUMERIC,
    lime_cooling_air_blower_speed NUMERIC,
    channel_temperature_1 NUMERIC,
    channel_temperature_2 NUMERIC,
    waste_gases_temp_outlet_kiln NUMERIC,
    waste_gases_temp_inlet_kiln_filter NUMERIC,
    shaft1_drawer_pipe_side_lime_temp NUMERIC,
    shaft1_drawer_skip_side_lime_temp NUMERIC,
    shaft2_drawer_pipe_side_lime_temp NUMERIC,
    shaft2_drawer_skip_side_lime_temp NUMERIC,
    combustion_air_pressure NUMERIC,
    lime_cooling_air_pressure NUMERIC,
    channel_air_pressure NUMERIC,
    shaft1_lances_cooling_air_pressure NUMERIC,
    shaft2_lances_cooling_air_pressure NUMERIC,
    shaft1_total_strokes INTEGER,
    shaft2_total_strokes INTEGER,
    natural_gas_temperature NUMERIC,
    natural_gas_pressure NUMERIC,
    natural_gas_output_regulator NUMERIC,
    hydraulic_oil_temperature NUMERIC,
    hydraulic_oil_pressure NUMERIC,
    waiting_time NUMERIC,
    unavailability_time NUMERIC,
    drawer_sampling NUMERIC,
    valves_time_maintenance NUMERIC,
    hydraulic_oil_unit_time_maintenance NUMERIC,
    hydraulic_oil_plant_time_maintenance NUMERIC,
    blower_time_maintenance NUMERIC,
    skip_time_maintenance NUMERIC,
    limestone_weighed_hopper_calibration NUMERIC,
    other_maintenance NUMERIC,
    mechanical_issue NUMERIC,
    electrical_issue NUMERIC,
    process_issue NUMERIC,
    other_issue NUMERIC
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.process_values (
        progressive_cycle_number,
        shaft_in_combustion,
        cycle_time,
        combustion_time,
        inversion_time,
        time_fuel_supply,
        limestone_for_cycle,
        lime_for_cycle,
        nominal_production,
        heat_consumption,
        fuel_for_cycle,
        fuel_flow,
        low_heat_value_air,
        stoichiometric_air,
        combustion_air_flow_theoretical,
        combustion_air_flow,
        combustion_air_index_excess_air,
        combustion_air_blower_speed,
        lime_cooling_air_flow_theoretical,
        lime_cooling_air_flow,
        lime_cooling_air_ratio,
        lime_cooling_air_blower_speed,
        channel_temperature_1,
        channel_temperature_2,
        waste_gases_temp_outlet_kiln,
        waste_gases_temp_inlet_kiln_filter,
        shaft1_drawer_pipe_side_lime_temp,
        shaft1_drawer_skip_side_lime_temp,
        shaft2_drawer_pipe_side_lime_temp,
        shaft2_drawer_skip_side_lime_temp,
        combustion_air_pressure,
        lime_cooling_air_pressure,
        channel_air_pressure,
        shaft1_lances_cooling_air_pressure,
        shaft2_lances_cooling_air_pressure,
        shaft1_total_strokes,
        shaft2_total_strokes,
        natural_gas_temperature,
        natural_gas_pressure,
        natural_gas_output_regulator,
        hydraulic_oil_temperature,
        hydraulic_oil_pressure,
        waiting_time,
        unavailability_time,
        drawer_sampling,
        valves_time_maintenance,
        hydraulic_oil_unit_time_maintenance,
        hydraulic_oil_plant_time_maintenance,
        blower_time_maintenance,
        skip_time_maintenance,
        limestone_weighed_hopper_calibration,
        other_maintenance,
        mechanical_issue,
        electrical_issue,
        process_issue,
        other_issue
    ) VALUES (
        progressive_cycle_number,
        shaft_in_combustion,
        cycle_time,
        combustion_time,
        inversion_time,
        time_fuel_supply,
        limestone_for_cycle,
        lime_for_cycle,
        nominal_production,
        heat_consumption,
        fuel_for_cycle,
        fuel_flow,
        low_heat_value_air,
        stoichiometric_air,
        combustion_air_flow_theoretical,
        combustion_air_flow,
        combustion_air_index_excess_air,
        combustion_air_blower_speed,
        lime_cooling_air_flow_theoretical,
        lime_cooling_air_flow,
        lime_cooling_air_ratio,
        lime_cooling_air_blower_speed,
        channel_temperature_1,
        channel_temperature_2,
        waste_gases_temp_outlet_kiln,
        waste_gases_temp_inlet_kiln_filter,
        shaft1_drawer_pipe_side_lime_temp,
        shaft1_drawer_skip_side_lime_temp,
        shaft2_drawer_pipe_side_lime_temp,
        shaft2_drawer_skip_side_lime_temp,
        combustion_air_pressure,
        lime_cooling_air_pressure,
        channel_air_pressure,
        shaft1_lances_cooling_air_pressure,
        shaft2_lances_cooling_air_pressure,
        shaft1_total_strokes,
        shaft2_total_strokes,
        natural_gas_temperature,
        natural_gas_pressure,
        natural_gas_output_regulator,
        hydraulic_oil_temperature,
        hydraulic_oil_pressure,
        waiting_time,
        unavailability_time,
        drawer_sampling,
        valves_time_maintenance,
        hydraulic_oil_unit_time_maintenance,
        hydraulic_oil_plant_time_maintenance,
        blower_time_maintenance,
        skip_time_maintenance,
        limestone_weighed_hopper_calibration,
        other_maintenance,
        mechanical_issue,
        electrical_issue,
        process_issue,
        other_issue
    );
END;
$$;