{
 "title": "Lime Klin - Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT name\nFROM config.endpoints\nORDER BY id ASC;"
   },
   {
    "name": "endpoint_id",
    "query": "SELECT id\nFROM config.endpoints\nWHERE name = '${endpoint}';"
   },
   {
    "name": "tag_table",
    "label": "Tag Table",
    "query": "SELECT name\nFROM config.tag_tables\nWHERE name IN (\n    SELECT unnest(\n            string_to_array(\n                replace(replace(replace(tag_tables, '[', ''), ']', ''), '\"', ''), ','\n            )\n        )\n    FROM config.endpoints\n    WHERE name = '${endpoint}'\n);"
   },
   {
    "name": "data_table",
    "label": "Table",
    "query": "SELECT process_table\nFROM config.tag_tables\nWHERE name = '${tag_table}'"
   },
   {
    "name": "lables",
    "label": "Lables",
    "query": "SELECT DISTINCT label\nFROM tags.${tag_table}\nORDER BY label ASC;"
   },
   {
    "name": "time_range",
    "label": "Time Range",
    "query": "SELECT (${__to} - ${__from})/1000"
   },
   {
    "name": "interval_text",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,1M,3M,6M,12M"
   },
   {
    "name": "interval",
    "query": "SELECT EXTRACT(EPOCH FROM '${interval_text}'::INTERVAL)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"text-align: left; font-weight: 500; margin-top: 50px; margin-bottom: 50px;\">\n    \n</h1>\n"
   }
  },
  {
   "title": "Endpoint Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Address\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Machine Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT machine\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id} "
    }
   ]
  },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__from}/1000) AS \"From\"\r\n"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_id \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "First ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_id \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Endpoint ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "Endpoint Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT protocol\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_TIMESTAMP(${__to}/1000) AS \"To\"\r\n"
    }
   ]
  },
  {
   "title": "Last ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_id \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cycle Disabled Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_disabled_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Time Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (${__to} - ${__from})/1000\r\n"
    }
   ]
  },
  {
   "title": "Unavailability Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT unavailability_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Waiting Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT waiting_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cycle_time, cycle_disabled_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  combustion_time, \r\n  inversion_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  mechanical_issue_time,\r\n  electrical_issue_time, \r\n  process_issue_time,\r\n  other_issue_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  valves_maint_time,\r\n  hyd_oil_unit_maint_time, \r\n  hyd_oil_plant_maint_time,\r\n  blower_maint_time,\r\n  skip_maint_time,\r\n  limestone_hopper_time,\r\n  other_maint_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Combustion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT combustion_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Fuel Supply Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_supply_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Inversion Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT inversion_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cycle_disabled_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT created_at,\r\n  other_issue_time,\r\n  mechanical_issue_time, \r\n  electrical_issue_time, \r\n  process_issue_time,\r\n  unavailability_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT created_at,\r\n  other_maint_time,\r\n  valves_maint_time,\r\n  hyd_oil_unit_maint_time, \r\n  hyd_oil_plant_maint_time,\r\n  blower_maint_time,\r\n  skip_maint_time,\r\n  limestone_hopper_time,\r\n  waiting_time\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Limestone / Lime",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "WITH temp AS (\r\n  SELECT \r\n    created_at,\r\n    CASE \r\n      WHEN ${interval} * INTERVAL '1 second' < INTERVAL '1 day' \r\n        THEN date_bin(${interval} * INTERVAL '1 second', created_at, TIMESTAMP 'epoch')\r\n      WHEN ${interval} * INTERVAL '1 second' < INTERVAL '7 days' \r\n        THEN date_trunc('day', created_at)\r\n      WHEN ${interval} * INTERVAL '1 second' < INTERVAL '21 days' \r\n        THEN date_trunc('week', created_at)\r\n      WHEN ${interval} * INTERVAL '1 second' < INTERVAL '70 days' \r\n        THEN date_trunc('month', created_at)\r\n      WHEN ${interval} * INTERVAL '1 second' < INTERVAL '365 days' \r\n        THEN date_trunc('quarter', created_at)\r\n      WHEN ${interval} * INTERVAL '1 second' >= INTERVAL '365 days' \r\n        THEN date_trunc('year', created_at)\r\n      ELSE date_trunc('day', created_at)\r\n    END AS time,\r\n    limestone_cycle,\r\n    lime_cycle\r\n  FROM ${data_table}\r\n  WHERE endpoint = ${endpoint_id}\r\n  AND $__timeFilter(created_at)\r\n)\r\nSELECT \r\n  time,\r\n  extract(epoch from (time + ${interval} * INTERVAL '1 second')::timestamp AT TIME ZONE 'UTC') * 1000 AS to_time, -- necessary for data link\r\n  SUM(limestone_cycle) AS total_limestone,\r\n  SUM(lime_cycle) AS total_lime\r\nFROM temp\r\nGROUP BY time\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  {
   "title": "Lime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, nominal_prod, lime_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n"
    }
   ]
  },
  {
   "title": "Nominal Production",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(nominal_prod) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(nominal_prod) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Lime Produced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous' AS period,\r\n    SUM(lime_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'current' AS period,\r\n    SUM(lime_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Nominal Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(nominal_prod) / 1000 / \r\n    ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  {
   "title": "Lime Rate",
   "type": "stat",
   "description": "Lime per hour - compared with previous period",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(lime_cycle) / 1000 / \r\n      ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  {
   "title": "Limestone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, limestone_cycle_setpoint, limestone_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Limestone SP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(limestone_cycle_setpoint) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(limestone_cycle_setpoint) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Limestone",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(limestone_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(limestone_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Limestone Rate SP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(limestone_cycle_setpoint) / 1000 / \r\n      ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  {
   "title": "Limestone Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(limestone_cycle) / 1000 / \r\n      ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  { "title": "Fuel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, heat_consumption_setpoint, heat_consumption\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND $__timeFilter(created_at)\r\n"
    }
   ]
  },
  {
   "title": "Heat Setpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous_interval' AS period,\r\n    SUM(heat_consumption_setpoint) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'selected_interval' AS period,\r\n    SUM(nominal_prod) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Lime Produced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'previous' AS period,\r\n    SUM(lime_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      -- start previous period\r\n      (TO_TIMESTAMP(${__from}/1000)\r\n       - (TO_TIMESTAMP(${__to}/1000) - TO_TIMESTAMP(${__from}/1000)))\r\n      -- end previous period\r\n      AND TO_TIMESTAMP(${__from}/1000)\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'current' AS period,\r\n    SUM(lime_cycle) AS total\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN\r\n      TO_TIMESTAMP(${__from}/1000)\r\n      AND TO_TIMESTAMP(${__to}/1000);\r\n"
    }
   ]
  },
  {
   "title": "Nominal Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(nominal_prod) / 1000 / \r\n    ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  {
   "title": "Lime Rate",
   "type": "stat",
   "description": "Lime per hour - compared with previous period",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Mg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(lime_cycle) / 1000 / \r\n      ((${__to} - ${__from})/1000 / 3600.0) AS rate\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND created_at BETWEEN TO_TIMESTAMP((${__from}/1000)) \r\n                          AND TO_TIMESTAMP(${__to}/1000)"
    }
   ]
  },
  {
   "title": "Heat Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cycle_id, heat_consumption_setpoint, heat_consumption\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Heat Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Natural Gas Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heat_consumption\r\nFROM (\r\n    SELECT created_at, heat_consumption\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 95 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_cycle_setpoint, fuel_cycle\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Natural Gas Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_cycle\r\nFROM (\r\n    SELECT created_at, fuel_cycle\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 103 },
   "targets": [
    {
     "rawSql": "SELECT created_at, natural_gas_temp\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 104 },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel_flow_setpoint, fuel_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Fuel Flow Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Natural Gas Regulator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT natural_gas_output_regulator\r\nFROM (\r\n    SELECT created_at, natural_gas_output_regulator\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fuel_flow\r\nFROM (\r\n    SELECT created_at, fuel_flow\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Combustion Air",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Combustion Air Flow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 104 },
     "targets": [
      {
       "rawSql": "SELECT created_at, combustion_air_flow_theo, combustion_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
      }
     ]
    },
    {
     "title": "Combustion Air Flow Theo",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT combustion_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
      }
     ]
    },
    {
     "title": "Waste Gasses Outlet Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT created_at, waste_gases_temp_outlet_kiln\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
      }
     ]
    },
    {
     "title": "Combution Air Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 108 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT heat_consumption\r\nFROM (\r\n    SELECT created_at, heat_consumption\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 109 },
     "targets": [
      {
       "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
      }
     ]
    },
    {
     "title": "Combustion Air Blower Speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 111 },
     "targets": [
      {
       "rawSql": "SELECT created_at, combustion_air_blower_speed_setpoint, combustion_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
      }
     ]
    },
    {
     "title": "Combustion Air Index Setpoint",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT combustion_air_index_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 112 },
     "targets": [
      {
       "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter, waste_gases_temp_outlet_kiln\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
      }
     ]
    },
    {
     "title": "Combution Air Index",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT combustion_air_index\r\nFROM (\r\n    SELECT created_at, combustion_air_index\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
      }
     ]
    },
    {
     "title": "Waste Gasses Filter Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT created_at, waste_gases_temp_inlet_kiln_filter\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
      }
     ]
    },
    {
     "title": "Combustion Air Index",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 118 },
     "targets": [
      {
       "rawSql": "SELECT created_at, combustion_air_index_setpoint, combustion_air_index\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
      }
     ]
    },
    {
     "title": "Combustion Air Blower Speed Setpoint",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT combustion_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
      }
     ]
    },
    {
     "title": "Combustion Air Pressure",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT created_at, combustion_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
      }
     ]
    },
    {
     "title": "Combution Air Blower Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 122 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT combustion_air_blower_speed\r\nFROM (\r\n    SELECT created_at, combustion_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Cool Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Cool Air Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 113 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_flow_theo, cool_air_flow\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 113 },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure, shaft2_lances_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 1 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft1_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM (\r\n    SELECT created_at, cool_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Blower Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_blower_speed_setpoint, cool_air_blower_speed\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_blower_speed\r\nFROM (\r\n    SELECT created_at, cool_air_blower_speed\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 121 },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio\r\nFROM (\r\n    SELECT created_at, cool_air_ratio\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Shaft 2 Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, shaft2_lances_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Flow Theoretical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 126 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_flow_theo\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 127 },
   "targets": [
    {
     "rawSql": "SELECT created_at, cool_air_ratio_setpoint, cool_air_ratio\r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\nORDER BY created_at DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Cool Air Lime Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at, lime_cool_air_pressure\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cool Air Ratio Setpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 130 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cool_air_ratio_setpoint\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\nORDER BY created_at DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  { "title": "Other Mesurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Strokes Shaft 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT shaft1_strokes\r\nFROM (\r\n    SELECT created_at, shaft1_strokes\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Strokes Shaft 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT shaft2_strokes\r\nFROM (\r\n    SELECT created_at, shaft2_strokes\r\n    FROM ${data_table}\r\n    WHERE endpoint = ${endpoint_id}\r\n    ORDER BY created_at DESC\r\n    LIMIT 10\r\n) subquery\r\nORDER BY created_at ASC;\r\n"
    }
   ]
  }
 ]
}