{
 "title": "Lime Klin - Cycle Details Navigation",
 "time": { "from": "2025-01-10T17:17:58.784Z", "to": "2025-01-10T17:17:58.784Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT name\nFROM config.endpoints\nORDER BY id ASC;"
   },
   {
    "name": "endpoint_id",
    "query": "SELECT id\nFROM config.endpoints\nWHERE name = '${endpoint}';"
   },
   {
    "name": "tag_table",
    "label": "Tag Table",
    "query": "SELECT name\nFROM config.tag_tables\nWHERE name IN (\n    SELECT unnest(\n            string_to_array(\n                replace(replace(replace(tag_tables, '[', ''), ']', ''), '\"', ''), ','\n            )\n        )\n    FROM config.endpoints\n    WHERE name = '${endpoint}'\n);"
   },
   {
    "name": "data_table",
    "label": "Table",
    "query": "SELECT process_table\nFROM config.tag_tables\nWHERE name = '${tag_table}'"
   },
   {
    "name": "cycle",
    "label": "Cycle ID",
    "query": "SELECT cycle_id\nFROM ${data_table} \nWHERE endpoint = ${endpoint_id} \n  AND $__timeFilter(created_at) \nORDER BY created_at \n"
   },
   {
    "name": "label",
    "label": "Label",
    "query": "SELECT DISTINCT label\nFROM tags.${tag_table}\nORDER BY label ASC;"
   },
   {
    "name": "tag_name",
    "query": "SELECT DISTINCT name \nFROM tags.${tag_table}\nWHERE label = '${label}'\n"
   },
   {
    "name": "tag_comment",
    "query": "SELECT comment \nFROM tags.${tag_table}\nWHERE name = '${tag_name}'"
   },
   {
    "name": "tag_other_name",
    "query": "SELECT DISTINCT name \nFROM tags.${tag_table}\nWHERE label = 'other'\n"
   },
   {
    "name": "tag_other_comment",
    "query": "SELECT DISTINCT comment \nFROM tags.${tag_table}\nWHERE label = 'other'\n"
   },
   {
    "name": "all_name",
    "query": "SELECT DISTINCT name \nFROM tags.${tag_table}\n"
   },
   {
    "name": "all_comment",
    "query": "SELECT comment \nFROM tags.${tag_table}\nWHERE name = '${all_name}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "canvas",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 204 },
     "targets": [
      {}
     ]
    },
    {
     "type": "canvas",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 204 },
     "targets": [
      {}
     ]
    },
    {
     "type": "canvas",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 204 },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 208 },
     "options": {
      "content": "<h1 style=\"text-align: left; font-weight: 500; margin-top: 50px; margin-bottom: 50px;\">\n    \n</h1>\n"
     }
    },
    {
     "title": "Endpoint Address",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 212 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT Address\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
      }
     ]
    },
    {
     "title": "Machine Name",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 6, "y": 212 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT machine\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id} "
      }
     ]
    },
    {
     "title": "Cycle ID",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 16, "y": 212 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cycle_id \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
      }
     ]
    },
    {
     "title": "Shaft",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 212 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT shaft_combustion \r\nFROM ${data_table} \r\nWHERE endpoint = ${endpoint_id} \r\n  AND cycle_id = ${cycle}"
      }
     ]
    },
    {
     "title": "Endpoint ID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 215 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT id\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
      }
     ]
    },
    {
     "title": "Endpoint Protocol",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 215 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT protocol\r\nFROM config.endpoints\r\nWHERE id = ${endpoint_id}"
      }
     ]
    }
   ]
  },
  { "title": "${label}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "${tag_name}",
   "type": "stat",
   "description": "${tag_comment}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "repeat": "tag_name",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${tag_name}\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "${all_name}",
   "type": "stat",
   "description": "${all_comment}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "repeat": "all_name",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${all_name}\r\nFROM ${data_table}\r\nWHERE endpoint = ${endpoint_id}\r\n  AND cycle_id BETWEEN ${cycle} - 1 AND ${cycle}\r\nORDER BY created_at DESC"
    }
   ]
  }
 ]
}